version: "3.3"
services:
  pyden-splunk:
    build:
      context: .
      dockerfile: splunk.dockerfile
    image: pyden-splunk
    container_name: pyden-splunk-1
    ports:
    - "8000:8000"
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "changeme1"
      SPLUNK_ANSIBLE_POST_TASKS: "file:///tmp/splunk_ansible_prep.yml"

  selenium:
    build:
      context: .
      dockerfile: selenium.dockerfile
    depends_on:
      - "pyden-splunk"
    image: pyden-selenium
    container_name: pyden-selenium-1
    entrypoint: ["python3", "/app/test/auto.py"]
    #entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      CI_PROJECT_DIR: "/app"
    volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/shm:/dev/shm
